### ISSUE TITLE
Grafana Dashboard in Helm Chart doesn't work

### ISSUE THREAD

**Issue by maxpain** [dragonflydb/dragonfly-operator#256]
Hello. I've deployed the dragonfly-operator Helm chart with the following values:

```yaml
serviceMonitor:
  enabled: true

grafanaDashboard:
  enabled: true
```

But getting this error:

<img width="1876" alt="image" src="https://github.com/user-attachments/assets/c238ceec-7f2c-4485-9d8b-28a9e8e7c8e7">

**Comment by Pothulapati** [comment]
@maxpain With Dragonfly, We don't deploy the prometheus. The issue seems to be that the datasource is misconfigured. Can you check for the same?

Thanks

**Comment by maxpain** [comment]
Yes, the provisioned dashboard doesn't have datasource variable

**Comment by Pothulapati** [comment]
You should be provisioning a prometheus instance right? if you already have one, add it into grafana and set it as the datasource of the dashboard.

**Comment by maxpain** [comment]
@Pothulapati Yes, I have configured Prometheus (VictoriaMetrics, which is much better) for my Grafana installation.
All my Grafana dashboards are declaratively provisioned via ConfigMaps. Almost all of them are from Helm charts and are working fine (CNPG, for example).

So, the Dragonfly grafana dashboard from the helm chart should be fixed.

**Comment by Pothulapati** [comment]
@maxpain Sure!

So, probably a way to pass the prometheus data source (including VictoriaMetrics) as a config through the helm chart?

**Comment by maxpain** [comment]
@Pothulapati I don't know how exactly, but all other helm charts with built-in grafana dashboards don't require configuring the Prometheus data source via helm values. They work out of the box.

**Comment by Pothulapati** [comment]
Looks like DS_Prometheus is a good answer where the user gets the option to select the datasource at the top.

**Comment by risen228** [comment]
I also encountered a similar problem - no datasource selection and the entire dashboard is empty with errors. I was able to fix it locally by adding [datasource selection similar to cloudnative-pg](https://github.com/cloudnative-pg/grafana-dashboards/blob/main/charts/cluster/grafana-dashboard.json#L9057-L9075) to `templating.list`:

```diff
- {
-   "hide": 2,
-   "name": "DS_PROMETHEUS",
-   "query": "prometheus",
-   "skipUrlSync": true,
-   "type": "constant"
- },
+ {
+   "current": {
+     "selected": false,
+     "text": "Prometheus",
+     "value": "prometheus"
+   },
+   "hide": 0,
+   "includeAll": false,
+   "label": "Datasource",
+   "multi": false,
+   "name": "DS_PROMETHEUS",
+   "options": [],
+   "query": "prometheus",
+   "queryValue": "",
+   "refresh": 1,
+   "regex": "",
+   "skipUrlSync": false,
+   "type": "datasource"
+ },
```

Can we try testing this solution? But I still don't understand what exactly is the reason for this behavior, maybe because the datasource is not called "Prometheus"? I also use Victoria Metrics, which has prometheus-compatible API, but there is no "Prometheus" in the name. And the input type is different, the current one is `constant`, and the one from cnpg is `datasource` - maybe this affects how grafana selects datasource and it fails for `constant`.

**Comment by Pothulapati** [comment]
Sure! @risen228 Can you raise a PR?

**Comment by risen228** [comment]
@Pothulapati done: https://github.com/dragonflydb/dragonfly-operator/pull/279
